# prometheus.yml
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: ['192.168.64.3:31316']
        labels:
          service: 'test-prom'
          group: 'production'
